In [1]:
import pandas as pd
import numpy as np

In [4]:
!pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

In [5]:
yfdf = pd.read_csv('data/forecasting data/macro_yahoo_vix_yieldcurve_dxy.csv')

gscpidf = pd.read_excel('data/forecasting data/gscpi_data.xls')

macrodf = pd.read_csv('data/forecasting data/merged_macro_dataset.csv')

tipsdf = pd.read_csv('data/forecasting data/us_treasury_tips_breakeven.csv')

In [6]:
yfdf.head()

         Date  VIX  UST10Y_pct  DX_FUT
0  1980-01-02  NaN       1.050     NaN
1  1980-01-03  NaN       1.060     NaN
2  1980-01-04  NaN       1.066     NaN
3  1980-01-07  NaN       1.063     NaN
4  1980-01-08  NaN       1.057     NaN

In [7]:
gscpidf.head()

   Unnamed: 0  Unnamed: 1  Unnamed: 2                           Unnamed: 3
0         NaN         NaN         NaN      NEW YORK FED  ECONOMIC RESEARCH
1         NaN         NaN         NaN                                  NaN
2         NaN         NaN         NaN  https://www.newyorkfed.org/research
3         NaN         NaN         NaN                                  NaN
4         NaN         NaN         NaN                                  NaN